### ISSUE TITLE
Crash on 0.3.2

### ISSUE THREAD

**Issue by xulaus** [xulaus/mr_bump#60]
```
@Rich ➜  tns.client rvm:(ruby-1.9.3@insight-app) git:(release/10.22.0) mr_bump
Have you already closed your PR?
[Y]es / [N]o: Y
/Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/gems/mr_bump-0.3.2/lib/mr_bump.rb:124:in `block in change_log_items_for_range': undefined method `[]' for nil:NilClass (NoMethodError)
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/gems/mr_bump-0.3.2/lib/mr_bump.rb:121:in `each_slice'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/gems/mr_bump-0.3.2/lib/mr_bump.rb:121:in `each'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/gems/mr_bump-0.3.2/lib/mr_bump.rb:121:in `map'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/gems/mr_bump-0.3.2/lib/mr_bump.rb:121:in `change_log_items_for_range'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/gems/mr_bump-0.3.2/bin/mr_bump:174:in `<top (required)>'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/bin/mr_bump:22:in `load'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/bin/mr_bump:22:in `<main>'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/bin/ruby_executable_hooks:15:in `eval'
	from /Users/richard/.rvm/gems/ruby-1.9.3-p545@insight-app/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by xulaus** [comment]
Fixed in 0.3.3
